version: '3.8'

services:
  # Base de datos MySQL compartida
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wordpress
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend

  # Primera instancia de WordPress
  wordpress1:
    image: wordpress:latest
    container_name: wordpress_1
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress1_data:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql

  # Segunda instancia de WordPress
  wordpress2:
    image: wordpress:latest
    container_name: wordpress_2
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - wordpress2_data:/var/www/html
    networks:
      - backend
    depends_on:
      - mysql

  # Nginx como reverse proxy
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend
    depends_on:
      - wordpress1
      - wordpress2

volumes:
  mysql_data:
  wordpress1_data:
  wordpress2_data:

networks:
  backend:
    driver: bridge